development:
  publishable_key:  'pk_test_NFLVkEHu8vDuNP7rZHAoGNx8'
  secret_key:  'sk_test_04p2UZn69e6RmAk2xTpkPevi'
production:
  publishable_key:  ENV['pk_test_NFLVkEHu8vDuNP7rZHAoGNx8']
  secret_key:  ENV['sk_test_04p2UZn69e6RmAk2xTpkPevi']
